### PR TITLE
Cache res.json calls

### PR DESCRIPTION
**Pull request by joaomoreno**
This PR enables caching of `res.json()`.

### CODE REVIEW

**Comment by bradoyler** [comment]
@joaomoreno This is not needed as `res.json` uses `res.send`.
See: https://github.com/strongloop/express/blob/master/lib/response.js#L249

**Comment by joaomoreno** [comment]
It misses the `Content-Type: application/json` header.

**Comment by bradoyler** [comment]
Aha! :100: 

Would u mind adding this mocha test?
```
    app.get('/hello-api', routeCache.cacheSeconds(3600), function(req, res){
        res.json({msg:'Hello'});
    });

    it('GET #9: res.json headers', function(done){
        agent
            .get('/hello-api')
            .expect('Content-Type', /json/).end(function(req, res){
                setTimeout(function() {
                    agent
                        .get('/hello-api')
                        .expect('Content-Type', /json/, done)
                }, 200);
            });
    });
```
to https://github.com/bradoyler/route-cache/blob/master/test/index.js 
Thanks!

**Comment by joaomoreno** [comment]
:+1:

**Pull request merged**
