### PR TITLE
upgrade eidetic dependency

### PR DESCRIPTION
**Pull request by danielkrainas**
I've been experiencing an issue where the eidetic@0.1.1's underscore dependency causes my application to crash on load because a global for `root` isn't defined. Upgrading eidetic to 0.3.1 fixes this thanks to that version dropping the underscore dependency all together. Tests still pass.

### CODE REVIEW

**Comment by bradoyler** [comment]
:+1: 
Here are the changes: https://github.com/mac-/eidetic/compare/0.1.1...master 
Thanks @danielkrainas

**Comment by danielkrainas** [comment]
Awesome! Any idea when you might publish again? I'm pointing my project at my fork for right now.

**Comment by bradoyler** [comment]
@danielkrainas pubbed!

**Comment by danielkrainas** [comment]
Appreciate it!

**Pull request merged**
